# 2012 

##  

Я хочу умереть, глядя в желтые листья.

Я хочу умереть, кутаясь в песочный плед.

Я хочу умереть, испачкав в краске кисти.

Я хочу умереть, оставляя на снегу след.

Но я умер вчера, до того как мне стукнуло двадцать,

Допивая горячий непентес и путаясь в дым,

Средь прочитанных книг, недописанных писем,

Где всегда оставался и буду один.

И я буду хотеть умереть пока буду дышать,

( и влюбляться поспешно)

Вновь и вновь чувствовать что-то внутри.

Для меня делать умереть — уж давно неизбежно,

Сколько будут гореть средь души пустыри.

> *осень 2012*


##

Мы вкалываем чувства,

— теряя вечность,

Впитываем боль, находя, что падение

— лишь путь в бесконечность.

Стираем клавишами строки

— звездного неба.

Все так же слепо ищем истоки

— счастья, но не находим,

И лишь тихо уходим.

С каждым новым вдохом

мы угасаем

Как недокуренные свечи, забывая,

Что мир сегодня — вечен.

> *лето 2012*


##

Мы сидели под бархатной луной,

Выкуривая воспоминания.

Пламя протягивало к нам свои сигаретные язычки.

Ты улыбался мне улыбкой,

В которой утонул бы сам океан.

И все было так же,

Как в серебристых снах,

Только немножечко волшебней.

> *лето 2012*


##

Осенними днями лета,

Сладкими минутами головокружения,

В дыму одиночества

Равносильно бессоннице осознание,

Что ты тот, ради кого хочется умереть.

Шуршание сигареты во время вдоха

Может сказать о нас больше,

Чем все пустые люди вокруг.

И не важно, сколько голосов звучало прежде.

Теперь ощутим лишь задорный смех нашей дружбы.

> *лето 2012*

