# 2017 

## ГОЛОС ТРАВМИРОВАННОГО ПОКОЛЕНИЯ

Тусклые кольца табачного дыма

Тянутся прочь.

Где бы ты ни был,

Окутанный в ночь,

Измучен до пота,

Уставший,

Пропитанный горестной рвотой,

Иссякший,

В объятья забвенья упавший,

Изрядно подвыпивший, но все таки ставший,

Голосом

Травмированного поколенья,

Что ганжей да хересом глушит

Сердцебиение

Той мелочной бляди,

Зовущейся музой,

Нещадно штурмующей

Шаткие шлюзы

И без того разбитого подсознанья,

Надежды дарующей,

Чарующей

Вновь,

В конечном итоге

Придумавшей

Любовь

— эту страшную штуку.

Вытяни руку

И сосчитай шрамы,

Порезы, окурков ожоги,

Сердечные раны.

Подумай о них как о свидетелях

Сгоревших мгновений,

Весны дуновений

Жизней прошедших,

Терзаний исполненных,

Но не ушедших

Бесследно.

Подумай о них

Как о тягостной дрёме,

О коме,

С которой ты вышел.

Теперь ты хоть знаешь о взломе

Собственной крыши.

Прими их как штампы того,

Что ты выжил.

Ведь где бы ты ни был,

Курящий,

Окутанный в ночь,

Болящий,

Шлющий поэзию прочь,

Иссякший,

Трясущийся хаотично,

В итоге ты жив,

Пускай и частично.

> *март 2017*


## СЕРОЕ НЕБО

В моем городе серое небо

И такие же серые птицы.

Оно видится где бы ты ни был,

Отражаясь в тумане сквозь лица

Мимолетно взглянувших прохожих

В глубину моего подсознанья,

Что уверены будто негоже

Быть в унынии столь юным созданиям.

Тем не менее, немое отчаянье

Никому не расскажет того,

Что нет узника в мире печальнее,

Чем поэт,

Что заперт

Внутри себя

Самого.

> *весна 2017*

##

Деревьев колкими ветвями

Перечеркнул мое безоблачное небо

Очередной поэт души печальной,

Обиженный на происки Вселенной.

Ведь очень может быть, что даже Бродский

В душе моей набедокурил от и до:

Мотив всех горестей грядет, увы, не плотский,

Иначе б сердцу уже было все равно.

А сны мои — гораздо ярче жизни —

Переплетаясь с памятью Ведут

Куда-то глубоко, где даже извне

Крымских закатов теплотой сквозит уют.

Мне с тишиною в темноте приходит море,

И волнами уводит за собой,

Будто в мое немыслимое горе

С прибоем принесет такой простой Покой.

Бредя по улицам до крайности пустынным,

Себя напоминаю только тень,

Чьи раны еще близко не остыли

И вовсе не готовы встретить новый день.

Вы говорите: «Умирать не ново!» только

Пожалуй, так бы всем стало жить проще.

Однако, новый день уже не не задворках,

И в мире вновь одним больным поэтом больше.

Сверкнули фары в предрассветной мгле,

И вопль тормозов пронзил могильный век.

Водитель выскочил, о смерти распинаясь мне,

А я стою и думаю: ни фонарей здесь, ни аптек.

Одна лишь ночь, которою я слышу,

Что пешеходный к черту замело,

Что с алкоголем людям явно сносит крышу…

— Увы, сама пьяна я только болью,

Да на снега мне как-то все равно.

И в ответ ухмыльнусь крайне мрачно,

Пускай брани давно не боюсь:

На тот свет не спешу однозначно,

Но и на этом задержаться не стремлюсь.

> *февраль 2017*

