# 2022 

##

Зданий кирпичных фасадами

Тянутся воспоминания,

А я брожу по ним

Не в силах передать того,

Что словно отзвук безысходности

Закрыло меня в собственной душе.

> *лето 2022*

##

Мы стояли у древнего дуба, окаймляющего Киев.

Мир казался таким безутешным

И в то же время полным причин продолжать свой путь.

За спиной красовались огни кем-то наполненных зданий.

У нас не было знаний (о них).

Лишь горстка любви и щепотка безмятежности,

Которую я утратила,

Когда выплакала все слезы,

Поливая чужие гортензии.

> *лето 2022*


##

Если ты я могла выстрелить

В брюхо каждого, кто сжег мосты за спинами моих близких,

Я все равно предпочла бы заткнуть дуло цветком.

Ведь мир — не математика,

И минус на минус

Никогда не даст плюс.

> *лето 2022*


## АКВАРИУМ

Мою судьбу отняли так жестоко

Едва ль исполнилось четверть века.

Я вышел в подъезд одинокий

В попытках отыскать в себе человека.

Встал на цыпочки, заглянул в окно,

А за ним лишь утро и улица.

Выкурил сигаретку, и уже все равно,

Что мечты и надежды не сбудутся.

За окном суматошно и сумрачно все

И люди как рыбки в аквариуме:

Несутся куда-то, ударяясь о дно,

Ну мы-то знаем, плавали.

Под окном один автомобиль

— и тот чужой.

Смотрю на него, и сам не свой.

Мол, в мире бессмысленно все, даже Солнце.

Закрой окошко и успокойся.

Одному прощаться с жизнью нелегко

Да как-то тесно,

Когда в собственной душе нет тебе места.

> *осень 2022*


##

Одиночество подобно покойному родственнику,

Пришедшему навестить тебя на пике отчаянья,

Откровенно осточертело.

Скитания по ветхим перекресткам,

Заносчивых идей и некогда всплывающих из коридоров вечности лиц

Лишено всякого смысла.

И только сумасшествие, укрывшее саваном

Еще вчера исправно тикающий рассудок

Привносит легкое очарование

В бой мыслей лопнувших сосудов.

> *август 2022*


## НИГДЕ НЕТ МЕСТА МНЕ

Нигде нет места мне.

В тени земного рая

Иду, стихи слагая

О были давних лет,

Где небеса, сгорая,

Под вечер проливают свет

На краешки могил моих друзей давно ушедших.

И снова шаль отчаянья оттягивает плечи.

Вдыхаешь — выдыхаешь лишь на миг,

Чтоб вспомнить тех, с кем некогда был счастлив.

Все до того, как мир утих.

И в океане погребенных далей

Гребу один.

Вместо русалок — продавщицы

С глазами полными вопросов.

Я не боюсь уже допросов:

Не умер — значит, победил.

Только кого?

Себя. Однако

Уже не выбраться из тени мрака

Тех городов, квартир и зданий,

Где атрибут лежит тоскливый

Моих садов.

Не нужно ксивы, чтоб в них войти:

Замок снесли,

Когда меня туда внесли

Вперед ногами, через гнет

Чужих смятений и хлопот.

И вот лежишь в сырой могиле,

А времена словно застыли.

По ним прошел последний бой

С судьбою или же с собой.

Там небеса в печальной брани

Висят как памятник усталый

И тихо близких голоса

Мне душу жалят как оса.

Закрой, мол, дверь, и уходи.

Но что за нею впереди?

Это не дверь, а крышка гроба,

Где желчи полная утроба

Все не дает покоя мыслям

В мирах, где мы растерянно зависли.

В закате, в браке и во тьме

Уже давно нет места мне.

> *осень 2022*


##

Осень без тебя — лишь тусклая пора года,

Где искры истлевших воспоминаний

Парят в кавалькаде ушедших событий.

Шахматный клуб — мое любимое воспоминание.

Во снах мы бродим по нему вместе, а наяву

— лишь колючая проволока перекрывает спуск к воде.

Мне представляется, как ты пишешь музыку

Один. В углу пианино, под которое нам так не удалось спеться.

Но как же здорово мы слышали этот мир. Вместе.

> *октябрь 2022*
