# 2023 

## КВАРТАЛЫ ДУШИ

От медитации — к прокрастинации,

Зачистке дум и модерации.

Затем — к полнейшей трепанации

Своей души.

Ты не спеши.

Пускай еще окурок теплится

Надежд, что обратились вечностью,

Смятений, тягот и погрешностей.

Просто дыши.

Беги туда, где ясно солнышко

И мысли легкие как перышко.

Побудь еще тем хоть мгновение.

Прими покой за сновидение.

Помнишь падение?

Винтовые лестницы с людьми случайными,

Поезд в мимолетные дали с подошвами рваными

И с до изнеможения выгнутыми шпалами.

Расцелуй их губами алыми!

Пройдись напоследок души кварталами

И помаши пешеходам усталым,

Да дай себе обещание:

Рассмеяться им на прощание.

> *февраль 2023*

##

Февраль. Уже поплакал, а что дальше?

Нет толку дни считать в календаре.

Уж лучше бы пройтись по лесной чаще

Да от пуль дыры сосчитать в стекле.

Ведь ими можно рисовать картины,

Не убивать отчаянных людей.

Кварталы стали крайне нелюдимы:

Полны одних аптек да фонарей.

Лить слезы — бесполезно и банально.

Как только их следы простыли

Глядишь в окно и думаешь сакрально:

Проснуться б в марте мне без этих взрывал.

До крайности обыденные думы,

От их обычности уже тошнит.

Нетривиально что сегодня, скажите?

Похоже, жить!

Да с головой своей дружить.

> *февраль 2023*


##

Огни зажглись. Мосты сгорели.

Когда такое небо над Землей

Войны не может быть,

Но она есть.

И негде в одиночестве присесть,

Чтобы понять:

Мы не вольны, увы, решать,

Какие мысли записать,

А скольким из тех слов истлеть,

Оставшись без издания.

И впредь

Плеть недосказанных мотивов

Будет хлестать рабов строптивых,

Что некогда решились петь.

Что есть мотив, коль не попытка

Души сказать чуть более столь малым

Другим умам — тоже усталым,

Которым не пришлось сгореть?

Скорей, истлеть,

Чтобы забыть все мимолетные исходы,

Событий, линий переходы

Из жизни в жизнь с одним концом,

И снова ветер под крыльцом

Шуршит, немного утомляя

Покой души,

Что в одиночестве сгорает.

> *весна 2023*
