# 2024

## ВИЗИТ

Одним дождливым летним днем

Я жизнью обозналась.

В плену неведомых оков

Моя судьба решалась.

Среди аллей цветущих роз,

Под небосводом, полным слез,

Но не моих — родных, которые смирились,

Что чадо их больно шизофренией.

И мне бы было весело узнать,

Как громко психиатры будут звать

Меня по имени в объятиях сновидений,

Когда на деле смешивают с тенью.

Им не дано понять моих терзаний наяву:

Пускай я пью таблетки и плыву

Куда меня послало наваждение.

Мир для меня — всего лишь сновидение,

Где не могу проснуться от кошмара

Да заглушить в душе пожара.

Смирюсь иль нет, мы все равно уснем

Одним дождливым летним днем.

> *август 2024*

## ЛЕС

Безоблачный вечер

Иронии вечной

Взгляды, фантазии на века.

Возьму коньяка

Да выпью беспечно,

Слизав лимонного сока

С жизни клинка.

Битые одиноко,

И все же не стану

Я праздности памятник возводить.

Притворно вздохну и перестану

Собою, той, что унылая, быть.

Нитью серебряной воспоминания

Стучат поднебесью в такт.

Одной лишь песнью мир не органичен.

Он вечен и без преград,

Что разум усталый

Рисует вяло

По памяти старой.

Беги без оглядки:

Забвение сладко.

Мотивы малюй,

Скройся в лес

— там больше небес.

Для них и рисуй.

Укройся под хвои волной,

Стань собой

И в тишине потанцуй.

> *осень 2024*

##

Осень. Открытие. Бар.

Людь сгущаются с сумраком дня.

Скрипки мотив дребезжит словно пар

Мелодий, что звонко звучат без меня.

Сапфиры да вывески — роскошь праздная,

Когда котелок подгорает.

Музыка вечера — такая разная,

Если мир без тебя убегает.

Один без любимых. Один в бытии:

Друзья рядом словно картонные.

Сидят, сном забывшись, да не знают они,

Какая ночь бездонная.

И губами прижмусь к вину,

А хотелось бы к микрофону.

Об иной судьбе не молю,

Но и этой не могу быть довольна.

> *сентябрь 2024*

##

Знецінені набутки билини

Мов підсвідомості, що ніччю сяють.

Подумки сплять батьківщини лани

Доки над ними пролітають

Картки примарні із життів минулих,

З дзвінкими посмішками,

Що вже перетнули

Кордони та замкнулись в своїх думах.

І презентований одному лиш собі

Йду коридорами спустошеного міста

Вогні чиїхсь квартир межують вдалині

Мої думки та вогники намиста

Тих фраз,

що я почув колись од вас,

До того як усі немов один

Сховалися за тінню чужини.

Все ж, крила любові колищаться

Сірому небу в такт

Насамоті краще пишеться

Чому й залишаюсь рад.

> *вересень 2024*


##

Я изгнана из своего мира.

Под сенью осеннего дня

Бреду городами сознания,

Сгорая день ото дня.

Бессознательное коллективное

Сжирает мой глас изнутри,

Пока душа строптивая

Не видит путей впереди.

Вновь чудится море и свечи,

Что тускло горят в тишине,

Возлагая на тонкие плечи

Глухую панихиду по мне.

Деревьев листья колышутся,

Затмленному схизой рассудку

Иные миры снова слышатся.

Там никто не подаст руку.

Я стану Буддой в Самбхога-Кайе

Откуда нет возврата,

Но знаю,

Там, где ум Нирване не подвластен,

Мышленье — бесполезная трата.

> *осень 2024*

## КОНДИНЦИОНЕР

Я хочу выброситься в океан.

Не тот, чем ты был для меня,

А тот, что поглубже

И явно почище.

Я мечтаю изливать мотивы

И опять дарить миру свет,

Но никогда не буду счастлива,

Ведь оставила сердце в шестидесятых.

Я не по тебе сгораю,

А умираю по любви,

Которая во мне была

До того, как мы встретились.

Я могла бы сигануть с обрыва

Элегантно скатиться кубарем вниз

Да раствориться в Бордо мирах,

Но все что мне сейчас интересно:

Льет ли за окном дождь,

Или это опять чей-то кондиционер

Протекает насквозь

Как моя крыша?

> *сентябрь 2024*

## ПРАХ

Струятся отчаянья капли,

Кипит котелок, аж вздымается,

Каркает Ворон под крышей

И лес пустотой обращается.

Рассудок оковами плавится,

Твой голос сердца отбивает такт.

Разве так от чертей избавляются?

Нет — их изгоняют в Ад.

И на краю забывшись дня,

Предприму последний шаг:

Захочу уйти в себя,

Но нет меня там — только прах.

Хотела прыгнуть из окна,

Да зацепилась ногой за форточку.

Мир разит как просроченная колбаса

И жить в нем больше не хочется.

Ничто уже не важно под Луной.

Даже души моей покой.

> *сентябрь 2024*


## МОЙ МИР

Пряди золотых волос

Окаймляют мудрый взгляд,

Что исходит от синих глаз

— дать совет всегда он рад.

Тихий, спокойный голос

Да такой же краткий нрав.

Справедливость во мне взрастивший

Он всегда был и будет прав.

Обожает с лимоном чай,

Быть в пути и занятия спортом.

Он мне в детстве сказал «Прощай!»,

И мир обратился жестоким.

Номер его телефона

В сердце моем как гравировка.

Я всегда о нем помню,

Как бы ни было плохо.

И с судов возвратившись усталый,

На миг присядет герой, наконец.

Мой мир без него исчезает.

Он — это мой Отец.

> *осень 2024*


## НЕСНОСНАЯ ЕРЕСЬ

Изумрудных глаз

Свет погас.

Потускнели мотивы.

Мы были

Чем-то вроде семьи.

Однако ушли

Твои нежные взгляды.

Я рада

Тому, что ты есть.

Не счесть

Тех строк,

Что звучат в моей голове.

Твой голос жесток,

Но только ко мне.

И города серость

— несносная ересь

Коль в нем без тебя веселиться.

Мне бы не спиться.

Рубаху надену твою

Как в бреду,

Немного повою

И тихо уйду

Туда, где сонеты

Разбитых сердец

Струятся над былью.

Мы были. Нас нет.

Со списка органов мой мозг исключен

Раз помнит твой запах - он обречен.

Мне нравился звон

Звезд, что сошлись

Когда столь негаданно мы разошлись

Вперед без оглядки.

С чего же так сладко

Тебя вспоминать?

В петлю ли опять

Я лезу бездумно

Да в мыслях так шумно.

И я бы сыграла на укулеле

Но знаю лишь один бой:

Других впитать не успела.

Как жаль, что ты не со мной.

> *сентябрь 2024*