project:
  type: book
  output-dir: docs

book:
  title: "Голос травмированного поколения"
  subtitle: 2012-2024
  author: "Александра Булгакова"
  date: "06-10-2024"
  page-navigation: true
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
  language: "ru"
  chapters:
    - index.qmd
    - 2012.qmd
    - 2017.qmd
    - 2020.qmd
    - 2022.qmd
    - 2023.qmd
    - 2024.qmd

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    number-sections: false
    search: true
    reader-mode: true
  pdf:
    output-file: "voice.pdf"
    # fontfamily: libertinus
    # pdf_engine: lualatex
    mainfont: Times New Roman
    papersize: a5paper
    # number-sections: false
  docx:
    output-file: "voice.docx"
    toc-title: "Оглавление"
  epub: 
    output-file: "voice.pdf"
    cover-image: cover.png



